worker_processes auto;

events {
    worker_connections 1024;
}

http {
    # Uses Header param provided by client request to ensure subsequent polling reaches the right server
    map $http_x_pdf_name $task_key {
        default $http_x_pdf_name;      
    }

    map $http_upgrade $connection_upgrade {
        default upgrade;
	''      close;
    }

    # Upstream for requests WITH a UUID (consistent hashing)
    upstream docling_backend_hash {
        hash $task_key consistent;
        server docling-serve-1:5001;
        server docling-serve-2:5001;
        server docling-serve-3:5001;
    }


    server {
        listen 80;

        location / {
		proxy_pass http://docling_backend_hash;

		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;

		proxy_set_header Host $host;

		proxy_read_timeout 600s;
		proxy_connect_timeout 60s;
		proxy_send_timeout 600s;

		proxy_buffering off;
        }
    }
}
